-- ============================================================
-- PROYECTO : Modelamiento BD Relacional - FASCOM
-- MOTOR    : Oracle Database
-- ============================================================

-- ============================================================
-- 1. TABLAS MAESTRAS
-- ============================================================

-- 1.1 CATEGORIA_EQUIPO
CREATE TABLE Categoria_Equipo (
    id_categoria     NUMBER(6) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria VARCHAR2(60) NOT NULL UNIQUE,
    descripcion      VARCHAR2(200)
);

-- 1.2 PROVEEDOR
CREATE TABLE Proveedor (
    id_proveedor  NUMBER(6) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruc           VARCHAR2(15) NOT NULL UNIQUE,
    razon_social  VARCHAR2(100) NOT NULL,
    telefono      VARCHAR2(15),
    email         VARCHAR2(100),
    direccion     VARCHAR2(150)
);

-- 1.3 SERVICIO
CREATE TABLE Servicio (
    id_servicio NUMBER(6) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(60) NOT NULL UNIQUE,
    descripcion VARCHAR2(200),
    precio_base NUMBER(10,2) NOT NULL
);

-- 1.4 PAQUETE_SERVICIO  (combos: internet + cable, etc.)
CREATE TABLE Paquete_Servicio (
    id_paquete  NUMBER(6) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(80) NOT NULL UNIQUE,
    descripcion VARCHAR2(200),
    precio      NUMBER(10,2) NOT NULL
);

-- 1.5 DETALLE_PAQUETE  (N:M entre Paquete y Servicio)
CREATE TABLE Detalle_Paquete (
    id_paquete  NUMBER(6) NOT NULL,
    id_servicio NUMBER(6) NOT NULL,
    PRIMARY KEY (id_paquete, id_servicio),
    FOREIGN KEY (id_paquete)  REFERENCES Paquete_Servicio(id_paquete),
    FOREIGN KEY (id_servicio) REFERENCES Servicio(id_servicio)
);

-- 1.6 CLIENTE
CREATE TABLE Cliente (
    id_cliente    NUMBER(6) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nro_documento VARCHAR2(15) NOT NULL UNIQUE,
    nombres       VARCHAR2(80) NOT NULL,
    apellidos     VARCHAR2(80) NOT NULL,
    direccion     VARCHAR2(150) NOT NULL,
    telefono      VARCHAR2(15),
    email         VARCHAR2(100),
    tipo_cliente  VARCHAR2(20) NOT NULL
);

-- 1.7 ESPECIALIDAD
CREATE TABLE Especialidad (
    id_especialidad NUMBER(6) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR2(60) NOT NULL UNIQUE,
    descripcion     VARCHAR2(150)
);

-- 1.8 TECNICO
CREATE TABLE Tecnico (
    id_tecnico    NUMBER(6) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nro_documento VARCHAR2(15) NOT NULL UNIQUE,
    nombres       VARCHAR2(80) NOT NULL,
    apellidos     VARCHAR2(80) NOT NULL,
    telefono      VARCHAR2(15),
    estado        VARCHAR2(15) DEFAULT 'Activo' NOT NULL
);

-- 1.9 TECNICO_ESPECIALIDAD  (N:M entre Técnico y Especialidad)
CREATE TABLE Tecnico_Especialidad (
    id_tecnico      NUMBER(6) NOT NULL,
    id_especialidad NUMBER(6) NOT NULL,
    PRIMARY KEY (id_tecnico, id_especialidad),
    FOREIGN KEY (id_tecnico)      REFERENCES Tecnico(id_tecnico),
    FOREIGN KEY (id_especialidad) REFERENCES Especialidad(id_especialidad)
);

-- ============================================================
-- 2. TABLAS TRANSACCIONALES
-- ============================================================

-- 2.1 ORDEN_INSTALACION
CREATE TABLE Orden_Instalacion (
    id_orden         NUMBER(8) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente       NUMBER(6) NOT NULL,
    id_tecnico       NUMBER(6) NOT NULL,
    fecha_registro   DATE DEFAULT SYSDATE NOT NULL,
    fecha_programada DATE NOT NULL,
    fecha_ejecucion  DATE,
    estado           VARCHAR2(15) DEFAULT 'Pendiente' NOT NULL,
    prioridad        VARCHAR2(10) DEFAULT 'Normal' NOT NULL,
    costo_total      NUMBER(10,2) DEFAULT 0,
    observaciones    VARCHAR2(250),
    FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente),
    FOREIGN KEY (id_tecnico) REFERENCES Tecnico(id_tecnico)
);

-- 2.2 DETALLE_ORDEN
CREATE TABLE Detalle_Orden (
    id_detalle  NUMBER(8) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden    NUMBER(8) NOT NULL,
    id_servicio NUMBER(6),
    id_paquete  NUMBER(6),
    cantidad    NUMBER(4) DEFAULT 1 NOT NULL,
    precio_unit NUMBER(10,2) NOT NULL,
    FOREIGN KEY (id_orden)    REFERENCES Orden_Instalacion(id_orden),
    FOREIGN KEY (id_servicio) REFERENCES Servicio(id_servicio),
    FOREIGN KEY (id_paquete)  REFERENCES Paquete_Servicio(id_paquete)
);

-- ============================================================
-- 3. TABLAS DE INVENTARIO
-- ============================================================

-- 3.1 EQUIPO (modelo del producto, sin serial)
CREATE TABLE Equipo (
    id_equipo         NUMBER(8) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR2(80) NOT NULL,
    id_categoria      NUMBER(6) NOT NULL,
    marca             VARCHAR2(60),
    modelo            VARCHAR2(60),
    stock_minimo      NUMBER(6) DEFAULT 0 NOT NULL,
    precio_referencia NUMBER(10,2),
    FOREIGN KEY (id_categoria) REFERENCES Categoria_Equipo(id_categoria)
);

-- 3.2 EQUIPO_SERIAL (una fila por unidad física)
CREATE TABLE Equipo_Serial (
    id_serial    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_equipo    NUMBER(8) NOT NULL,
    codigo_serial VARCHAR2(40) NOT NULL UNIQUE,
    estado       VARCHAR2(20) DEFAULT 'Disponible' NOT NULL,
    fecha_ingreso DATE DEFAULT SYSDATE NOT NULL,
    FOREIGN KEY (id_equipo) REFERENCES Equipo(id_equipo)
);

-- 3.3 COMPRA_INVENTARIO (cabecera)
CREATE TABLE Compra_Inventario (
    id_compra    NUMBER(8) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor NUMBER(6) NOT NULL,
    fecha_compra DATE DEFAULT SYSDATE NOT NULL,
    total        NUMBER(10,2) DEFAULT 0,
    FOREIGN KEY (id_proveedor) REFERENCES Proveedor(id_proveedor)
);

-- 3.4 DETALLE_COMPRA
CREATE TABLE Detalle_Compra (
    id_detalle_compra NUMBER(8) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_compra         NUMBER(8) NOT NULL,
    id_equipo         NUMBER(8) NOT NULL,
    cantidad          NUMBER(6) NOT NULL,
    precio_unit       NUMBER(10,2) NOT NULL,
    FOREIGN KEY (id_compra) REFERENCES Compra_Inventario(id_compra),
    FOREIGN KEY (id_equipo) REFERENCES Equipo(id_equipo)
);

-- 3.5 CONSUMO_EQUIPO
CREATE TABLE Consumo_Equipo (
    id_consumo    NUMBER(8) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden      NUMBER(8) NOT NULL,
    id_equipo     NUMBER(8) NOT NULL,
    cantidad      NUMBER(4) NOT NULL,
    fecha_consumo DATE DEFAULT SYSDATE NOT NULL,
    FOREIGN KEY (id_orden)  REFERENCES Orden_Instalacion(id_orden),
    FOREIGN KEY (id_equipo) REFERENCES Equipo(id_equipo)
);

-- 3.6 MOVIMIENTO_INVENTARIO (trazabilidad de stock)
CREATE TABLE Movimiento_Inventario (
    id_movimiento NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_equipo     NUMBER(8) NOT NULL,
    tipo          VARCHAR2(10) NOT NULL,
    cantidad      NUMBER(6) NOT NULL,
    fecha         DATE DEFAULT SYSDATE NOT NULL,
    motivo        VARCHAR2(150),
    id_orden      NUMBER(8),
    id_compra     NUMBER(8),
    FOREIGN KEY (id_equipo) REFERENCES Equipo(id_equipo),
    FOREIGN KEY (id_orden)  REFERENCES Orden_Instalacion(id_orden),
    FOREIGN KEY (id_compra) REFERENCES Compra_Inventario(id_compra)
);

-- ============================================================
-- 4. DATOS DE PRUEBA
-- ============================================================

INSERT INTO Categoria_Equipo (nombre_categoria, descripcion) VALUES ('Router','Equipos de internet');
INSERT INTO Categoria_Equipo (nombre_categoria, descripcion) VALUES ('Cable','Cables de red');
INSERT INTO Categoria_Equipo (nombre_categoria, descripcion) VALUES ('Cámara','Cámaras CCTV');
INSERT INTO Categoria_Equipo (nombre_categoria, descripcion) VALUES ('Conector','Conectores');
INSERT INTO Categoria_Equipo (nombre_categoria, descripcion) VALUES ('Decodificador','Equipos de cable TV');

INSERT INTO Proveedor (ruc, razon_social, telefono, email, direccion) VALUES
('20123456789','TecnoImport SAC','987654321','ventas@tecnoimport.pe','Av. Arequipa 123 - Lima');
INSERT INTO Proveedor (ruc, razon_social, telefono, email, direccion) VALUES
('20987654321','Seguridad Total EIRL','987111222','contacto@segtotal.pe','Calle Los Olivos 456 - Ica');

INSERT INTO Servicio (nombre, descripcion, precio_base) VALUES ('Internet','Internet residencial',120.00);
INSERT INTO Servicio (nombre, descripcion, precio_base) VALUES ('Cable TV','Sistema de cable',80.00);
INSERT INTO Servicio (nombre, descripcion, precio_base) VALUES ('CCTV','Cámaras de seguridad',250.00);

INSERT INTO Paquete_Servicio (nombre, descripcion, precio) VALUES
('Dúo Internet + Cable','Internet y cable TV juntos',180.00);
INSERT INTO Paquete_Servicio (nombre, descripcion, precio) VALUES
('Triple Seguridad','Internet + Cable + CCTV',400.00);

INSERT INTO Detalle_Paquete (id_paquete, id_servicio) VALUES (1,1);
INSERT INTO Detalle_Paquete (id_paquete, id_servicio) VALUES (1,2);
INSERT INTO Detalle_Paquete (id_paquete, id_servicio) VALUES (2,1);
INSERT INTO Detalle_Paquete (id_paquete, id_servicio) VALUES (2,2);
INSERT INTO Detalle_Paquete (id_paquete, id_servicio) VALUES (2,3);

INSERT INTO Cliente (nro_documento, nombres, apellidos, direccion, telefono, email, tipo_cliente) VALUES
('45678912','Juan','Pérez','Av. Lima 123','956111222','juan@mail.com','Vivienda');
INSERT INTO Cliente (nro_documento, nombres, apellidos, direccion, telefono, email, tipo_cliente) VALUES
('20456789123','Comercial El Sol','','Calle Comercio 456','956333444','elsol@mail.com','Comercial');
INSERT INTO Cliente (nro_documento, nombres, apellidos, direccion, telefono, email, tipo_cliente) VALUES
('78912345','María','Gómez','Jr. Progreso 789','956555666','maria@mail.com','Vivienda');

INSERT INTO Especialidad (nombre, descripcion) VALUES ('Internet','Redes y routers');
INSERT INTO Especialidad (nombre, descripcion) VALUES ('Cable TV','Instalación coaxial');
INSERT INTO Especialidad (nombre, descripcion) VALUES ('CCTV','Videovigilancia');

INSERT INTO Tecnico (nro_documento, nombres, apellidos, telefono) VALUES
('12345678','Carlos','Ramírez','987111222');
INSERT INTO Tecnico (nro_documento, nombres, apellidos, telefono) VALUES
('87654321','Luis','Torres','987333444');
INSERT INTO Tecnico (nro_documento, nombres, apellidos, telefono) VALUES
('11223344','Pedro','Vargas','987555666');

INSERT INTO Tecnico_Especialidad (id_tecnico, id_especialidad) VALUES (1,1);
INSERT INTO Tecnico_Especialidad (id_tecnico, id_especialidad) VALUES (2,3);
INSERT INTO Tecnico_Especialidad (id_tecnico, id_especialidad) VALUES (3,2);
INSERT INTO Tecnico_Especialidad (id_tecnico, id_especialidad) VALUES (1,2);

INSERT INTO Equipo (nombre, id_categoria, marca, modelo, stock_minimo, precio_referencia) VALUES
('Router WiFi','1','TP-Link','Archer C6',5,180.00);
INSERT INTO Equipo (nombre, id_categoria, marca, modelo, stock_minimo, precio_referencia) VALUES
('Cámara Domo HD','3','Hikvision','DS-2CE',3,220.00);
INSERT INTO Equipo (nombre, id_categoria, marca, modelo, stock_minimo, precio_referencia) VALUES
('Cable UTP Cat6','2','Genérico','Cat6',100,2.50);
INSERT INTO Equipo (nombre, id_categoria, marca, modelo, stock_minimo, precio_referencia) VALUES
('Decodificador HD','5','Motorola','HD-D2',2,150.00);
INSERT INTO Equipo (nombre, id_categoria, marca, modelo, stock_minimo, precio_referencia) VALUES
('Conector RJ45','4','Genérico','RJ45',50,1.00);

INSERT INTO Equipo_Serial (id_equipo, codigo_serial, estado) VALUES (1,'RTR-0001','Disponible');
INSERT INTO Equipo_Serial (id_equipo, codigo_serial, estado) VALUES (1,'RTR-0002','Disponible');
INSERT INTO Equipo_Serial (id_equipo, codigo_serial, estado) VALUES (1,'RTR-0003','Disponible');
INSERT INTO Equipo_Serial (id_equipo, codigo_serial, estado) VALUES (2,'CAM-0001','Disponible');
INSERT INTO Equipo_Serial (id_equipo, codigo_serial, estado) VALUES (2,'CAM-0002','Disponible');

INSERT INTO Compra_Inventario (id_proveedor, total) VALUES (1, 540.00);
INSERT INTO Detalle_Compra (id_compra, id_equipo, cantidad, precio_unit) VALUES (1,1,3,180.00);

INSERT INTO Orden_Instalacion (id_cliente, id_tecnico, fecha_programada, estado, prioridad) VALUES
(1,1,SYSDATE+2,'Pendiente','Normal');
INSERT INTO Orden_Instalacion (id_cliente, id_tecnico, fecha_programada, estado, prioridad) VALUES
(2,2,SYSDATE+1,'En proceso','Alta');
INSERT INTO Orden_Instalacion (id_cliente, id_tecnico, fecha_programada, fecha_ejecucion, estado) VALUES
(3,3,SYSDATE-3,SYSDATE-2,'Completada');

INSERT INTO Detalle_Orden (id_orden, id_servicio, cantidad, precio_unit) VALUES (1,1,1,120.00);
INSERT INTO Detalle_Orden (id_orden, id_paquete, cantidad, precio_unit) VALUES (2,2,1,400.00);
INSERT INTO Detalle_Orden (id_orden, id_servicio, cantidad, precio_unit) VALUES (3,2,1, 80.00);

COMMIT;

-- ============================================================
-- 5. OBJETOS PROGRAMABLES
-- ============================================================

-- 5.1 TRIGGER: al insertar consumo, descuenta stock y registra movimiento
CREATE OR REPLACE TRIGGER trg_consumo_stock
AFTER INSERT ON Consumo_Equipo
FOR EACH ROW
BEGIN
    INSERT INTO Movimiento_Inventario (id_equipo, tipo, cantidad, motivo, id_orden)
    VALUES (:NEW.id_equipo, 'Salida', :NEW.cantidad, 'Consumo en orden', :NEW.id_orden);

    UPDATE Equipo_Serial
       SET estado = 'Instalado'
     WHERE id_equipo = :NEW.id_equipo
       AND estado = 'Disponible'
       AND ROWNUM <= :NEW.cantidad;
END;
/

-- 5.2 TRIGGER: al registrar compra, genera entrada en inventario
CREATE OR REPLACE TRIGGER trg_compra_entrada
AFTER INSERT ON Detalle_Compra
FOR EACH ROW
BEGIN
    INSERT INTO Movimiento_Inventario (id_equipo, tipo, cantidad, motivo, id_compra)
    VALUES (:NEW.id_equipo, 'Entrada', :NEW.cantidad, 'Compra a proveedor', :NEW.id_compra);
END;
/

-- 5.3 PROCEDIMIENTO: registrar orden completa
CREATE OR REPLACE PROCEDURE sp_registrar_orden (
    p_id_cliente  IN NUMBER,
    p_id_tecnico  IN NUMBER,
    p_fecha       IN DATE,
    p_id_servicio IN NUMBER,
    p_precio      IN NUMBER
) AS
    v_id_orden NUMBER;
BEGIN
    INSERT INTO Orden_Instalacion (id_cliente, id_tecnico, fecha_programada, estado)
    VALUES (p_id_cliente, p_id_tecnico, p_fecha, 'Pendiente');

    SELECT MAX(id_orden) INTO v_id_orden FROM Orden_Instalacion;

    INSERT INTO Detalle_Orden (id_orden, id_servicio, cantidad, precio_unit)
    VALUES (v_id_orden, p_id_servicio, 1, p_precio);

    UPDATE Orden_Instalacion
       SET costo_total = p_precio
     WHERE id_orden = v_id_orden;

    COMMIT;
END;
/

-- 5.4 PROCEDIMIENTO: registrar compra de inventario
CREATE OR REPLACE PROCEDURE sp_registrar_compra (
    p_id_proveedor IN NUMBER,
    p_id_equipo    IN NUMBER,
    p_cantidad     IN NUMBER,
    p_precio       IN NUMBER
) AS
    v_id_compra NUMBER;
BEGIN
    INSERT INTO Compra_Inventario (id_proveedor, total)
    VALUES (p_id_proveedor, p_cantidad * p_precio);

    SELECT MAX(id_compra) INTO v_id_compra FROM Compra_Inventario;

    INSERT INTO Detalle_Compra (id_compra, id_equipo, cantidad, precio_unit)
    VALUES (v_id_compra, p_id_equipo, p_cantidad, p_precio);

    COMMIT;
END;
/

-- 5.5 FUNCIÓN: stock disponible por categoría
CREATE OR REPLACE FUNCTION fn_stock_categoria (p_id_categoria IN NUMBER)
RETURN NUMBER
IS
    v_total NUMBER;
BEGIN
    SELECT NVL(COUNT(*), 0) INTO v_total
    FROM Equipo_Serial es
    JOIN Equipo e ON e.id_equipo = es.id_equipo
    WHERE e.id_categoria = p_id_categoria
      AND es.estado = 'Disponible';
    RETURN v_total;
END;
/

-- 5.6 FUNCIÓN: costo total de una orden
CREATE OR REPLACE FUNCTION fn_costo_orden (p_id_orden IN NUMBER)
RETURN NUMBER
IS
    v_total NUMBER;
BEGIN
    SELECT NVL(SUM(cantidad * precio_unit), 0) INTO v_total
    FROM Detalle_Orden
    WHERE id_orden = p_id_orden;
    RETURN v_total;
END;
/

-- 5.7 CURSOR: equipos con stock crítico (bajo mínimo)
DECLARE
    CURSOR cur_stock_critico IS
        SELECT e.nombre, e.stock_minimo, COUNT(es.id_serial) AS disponibles
        FROM Equipo e
        LEFT JOIN Equipo_Serial es
               ON es.id_equipo = e.id_equipo
              AND es.estado = 'Disponible'
        GROUP BY e.nombre, e.stock_minimo
        HAVING COUNT(es.id_serial) <= e.stock_minimo;

    v_nombre VARCHAR2(80);
    v_min    NUMBER(6);
    v_disp   NUMBER(6);
BEGIN
    OPEN cur_stock_critico;
    LOOP
        FETCH cur_stock_critico INTO v_nombre, v_min, v_disp;
        EXIT WHEN cur_stock_critico%NOTFOUND;
        INSERT INTO Movimiento_Inventario (id_equipo, tipo, cantidad, motivo)
        SELECT id_equipo, 'Ajuste', 0, 'Stock crítico: ' || v_nombre || ' (' || v_disp || '/' || v_min || ')'
        FROM Equipo WHERE nombre = v_nombre;
    END LOOP;
    CLOSE cur_stock_critico;
    COMMIT;
END;
/

-- 5.8 CURSOR: carga de trabajo por técnico
DECLARE
    CURSOR cur_carga IS
        SELECT t.nombres || ' ' || t.apellidos AS tecnico, COUNT(o.id_orden) AS total
        FROM Tecnico t
        LEFT JOIN Orden_Instalacion o ON o.id_tecnico = t.id_tecnico
        GROUP BY t.nombres, t.apellidos;

    v_tecnico VARCHAR2(160);
    v_total   NUMBER;
BEGIN
    OPEN cur_carga;
    LOOP
        FETCH cur_carga INTO v_tecnico, v_total;
        EXIT WHEN cur_carga%NOTFOUND;
        -- Solo se procesa si tiene más de 0 órdenes
        IF v_total > 0 THEN
            NULL; -- aquí podría registrarse en otra tabla de resumen
        END IF;
    END LOOP;
    CLOSE cur_carga;
END;
/

-- ============================================================
-- 6. VISTAS (reportes rápidos)
-- ============================================================

CREATE OR REPLACE VIEW vw_stock_critico AS
SELECT e.nombre AS equipo,
       c.nombre_categoria AS categoria,
       e.stock_minimo,
       COUNT(es.id_serial) AS disponibles
FROM Equipo e
JOIN Categoria_Equipo c ON c.id_categoria = e.id_categoria
LEFT JOIN Equipo_Serial es
       ON es.id_equipo = e.id_equipo
      AND es.estado = 'Disponible'
GROUP BY e.nombre, c.nombre_categoria, e.stock_minimo
HAVING COUNT(es.id_serial) <= e.stock_minimo;

CREATE OR REPLACE VIEW vw_ordenes_por_estado AS
SELECT estado, COUNT(*) AS total
FROM Orden_Instalacion
GROUP BY estado;

CREATE OR REPLACE VIEW vw_ingresos_por_mes AS
SELECT TO_CHAR(fecha_registro,'YYYY-MM') AS mes,
       SUM(costo_total) AS ingresos
FROM Orden_Instalacion
WHERE estado = 'Completada'
GROUP BY TO_CHAR(fecha_registro,'YYYY-MM');

CREATE OR REPLACE VIEW vw_equipos_instalados AS
SELECT c.nombres || ' ' || c.apellidos AS cliente,
       o.id_orden,
       e.nombre AS equipo,
       ce.cantidad
FROM Consumo_Equipo ce
JOIN Orden_Instalacion o ON o.id_orden = ce.id_orden
JOIN Cliente c          ON c.id_cliente = o.id_cliente
JOIN Equipo e           ON e.id_equipo = ce.id_equipo;

-- ============================================================
-- 7. PRUEBAS
-- ============================================================

-- Ver stock disponible de routers (categoría 1)
SELECT fn_stock_categoria(1) AS routers_disponibles FROM dual;

-- Ver costo total de la orden 1
SELECT fn_costo_orden(1) AS costo FROM dual;

-- Ver vistas
SELECT * FROM vw_stock_critico;
SELECT * FROM vw_ordenes_por_estado;
SELECT * FROM vw_ingresos_por_mes;

-- Registrar consumo (dispara trigger)
INSERT INTO Consumo_Equipo (id_orden, id_equipo, cantidad) VALUES (2, 2, 2);
COMMIT;

-- Ver movimientos
SELECT * FROM Movimiento_Inventario ORDER BY id_movimiento;
